.github/ISSUE_TEMPLATE/1-feature.md, .github/ISSUE_TEMPLATE/2-bug.md, .github/ISSUE_TEMPLATE/3-documentation.md, .github/ISSUE_TEMPLATE/4-technical-debt.md, .github/ISSUE_TEMPLATE/5-update-dependencies.md, .github/ISSUE_TEMPLATE/config.yml, .prettierrc.json
Including a set of issue templates and config to be used in the repository. Also, override the prettier tab config for Markdown files.
=> Chore: Add GitHub issue templates

apps/web/package.json, package.json, packages/eslint-config-cartesi/package.json, yarn.lock
Opening URL https://cartesiscan.io/applications/0x0974cc873df893b302f6be7ecf4f9d4b1a15c366 directly, without navigating, is giving a 500 error.
Checking the server logs it looks like it's related to issue https://github.com/vercel/next.js/issues/49169
This PR updates next to 13.5, as suggested by the issue.
ps: it also upgrades all other dependencies
=> Upgrade next to 13.5

apps/web/package.json, apps/web/test/components/address.test.tsx, apps/web/test/utils/WithMantineTheme.tsx, apps/web/tsconfig.json, apps/web/vitest-setup.ts, apps/web/vitest.config.mts, package.json, packages/rollups-wagmi/package.json, packages/ui/src/InputDetails/InputDetailsContext.tsx, yarn.lock
Code changes to add Vitest to the web application. I also made changes to the rollups-wagmi generation and entry points declaration. 
Changes: 
* Added configuration for Vitest + initial test case for the Web application. 
* Made rollups-wagmi an ESM library instead of focusing on CJS. CJS is still generated, though.
* Added some explicit TS types declaration to remove some squiggly lines that show up after upgrade, and I also silenced one line for the Ramda `pick`.
=> Feat: Add test framework to web app

apps/web/src/app/applications/page.tsx, apps/web/src/app/shell.tsx
Code changes to give access to the applications page from a link in the header rather than clicking an application followed by a click in the breadcrumb. Also, a change in the label for the number of items loaded in the list of applications from `inputs` to `applications`.
=> Adding access to Applications page

apps/web/.env.template, apps/web/src/providers/walletProvider.tsx, turbo.json
Code changes to support alchemy provider. When the `NEXT_PUBLIC_ALCHEMY_API_KEY` is available the `alchemyProvider()` builder function will be available. That does not remove the `publicProvider` from the list is just an addition.
=> Add alchemy-provider support.

apps/web/.env.mainnet, apps/web/.env.sepolia, apps/web/codegen.ts
Replace the Subsquid service domain address in favour of our domain. We are not using the Subsquid aquarium service at the moment. So, at this point, any calls to that endpoint will fail.
=> chore: Replace Subsquid API address.

apps/web/src/app/shell.tsx
Code changes to include a navigation link to the applications page and deposit actions that work for small screens.
=> refactor: Add link to /applications and deposit actions for small screens

apps/web/package.json, apps/workshop/package.json, yarn.lock
Changes to upgrade Rainbowkit to its latest version. Below a list of changelogs with some highlights of what are coming with the upgrade.
What's  new:
* Mostly towards improvements for desktop  wallet download links support [Changelog v1.20](https://github.com/rainbow-me/rainbowkit/releases/tag/@rainbow-me/rainbowkit@1.2.0)
* Highlighting Support for locations on auth flow for SIWE (Sign-in with Ethereum), and other fixes and improvements [v.1.1.4](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.1.4)
* Mainly support to new wallets:
* [v1.1.3](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.1.3)
* [v1.1.2](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.1.2)
* Mainly fixes and …
=> Chore: Update Rainbowkit

apps/web/package.json, apps/web/src/providers/walletProvider.tsx, yarn.lock
Upgrading rainbow-kit and wagmi to its latest versions. Also removed the argent-wallet from the options.
Wagmi release: https://github.com/wevm/wagmi/releases/tag/wagmi%401.4.12
Rainbow-kit release: https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.3.1
=> chore: Update versions rainbow-kit@1.3.1 and wagmi@1.4.12

apps/web/src/app/applications/[address]/page.tsx, apps/web/src/components/inputRow.tsx, apps/web/src/components/inputsTable.tsx, apps/web/src/components/tableResponsiveWrapper.tsx, apps/web/src/hooks/useElementVisibility.tsx, apps/web/test/components/inputsTable.test.tsx, apps/web/test/hooks/useElementVisibility.test.tsx
This PR introduces:
1. **Responsive Table Wrapper Component:** A new component to make tables have overflow between screen sizes.
2. **Wrapper Integration:** Applied the wrapper to our InputsTable component for enhanced responsiveness.
3. **`use-intersection` from Mantine:** Implemented this hook for better display visibility of our tables.
These changes aim to improve UI responsiveness and user experience.
Closing #67
=> 67. Add responsiveness to the tables

apps/web/src/components/layout/shell.tsx
=> #77 Header UI becomes distorted in tablet view

.vscode/settings.json, apps/web/src/app/layout.tsx, apps/web/src/components/layout/shell.tsx
Code changes to close the mobile menu when clicking one of the links [`inputs`, `applications`, `home`] so the user have a feedback that the navigation happen. Also, changes to fix a bug that causes the send-transaction to not be enabled when entering the application with a wallet connected (only in dark-mode gif below). Ps: that also affected the menu for small devices, the send-tx would continue to be disabled even though there is an account connected.
<details>
<summary><h3>Before Fix</h3> </summary>
</details>
<details>
<summary><h3>After Fix</h3> </summary>
</details>
=> Feature: Close menu after clicking link

apps/workshop/package.json, yarn.lock
Upgrade [Mantine](https://mantine.dev/) to v7.5.0 to avoid having multiple versions between the workshop app and the UI package. That fixes the problem where some stories will not render in the deployed workshop app (In Dev mode, it works), as depicted in the screenshot below.
=> Fix: Deployed Workshop

apps/web/src/lib/query.ts, apps/web/test/lib/query.test.ts
Code changes for search to behave as expected on`/inputs` and `/applications/address` pages respectively. Currently, it is not listing the application-specific inputs it has the same behaviour as listing all inputs. 
Changes: 
* Refactor the lib/query to use a few functions from `viem` and change the logic order, leaving the higher precedence to be when the `application` is defined and not the other way around. 
* Added test cases for the lib/query.
=> Fix: Application page inputs

.github/workflows/ci.yml, apps/web/graphql/rollups/queries.graphql, apps/web/src/components/inputs/inputDetailsView.tsx, apps/web/src/components/inputs/voucherExecution.tsx, apps/web/test/components/inputs/inputDetailsView.test.tsx, apps/web/test/components/inputs/voucherExecution.test.tsx, apps/web/test/utils/dataSamples.ts, apps/web/vitest.config.mts, apps/workshop/src/stories/InputDetails.stories.tsx, packages/rollups-wagmi/tsconfig.json, packages/rollups-wagmi/wagmi.config.ts, packages/ui/src/InputDetails/VoucherContent.tsx, packages/ui/vitest.config.mts
I added the voucher execution logic in a component called `VoucherExecution` located in `apps/web`. For testing of this logic I used the following [dapp](https://github.com/WeAreProductive/drawing-DApp/) which comes will functionality for adding inputs with vouchers.
=> #101 Add voucher execution

apps/web/test/components/inputs/inputDetailsView.test.tsx
Fixing build failure due to a missing mock on Vitest after merging voucher execution PR. It was a bit behind compared with the main, and the addition of ERC-721 was not a problem until the merge & squash was done. No real damage on Vercel deployments, only the Github action that failed.
=> Fix: Mock type for @cartesi/rollups-wagmi on InputDetailsView test file

apps/web/src/components/applications/applicationsTable.tsx, apps/web/src/components/inputs/inputs.tsx, apps/web/src/components/inputs/inputsTable.tsx, apps/web/src/components/latestEntriesTable.tsx, apps/web/src/components/search.tsx, apps/web/src/providers/theme.tsx, apps/web/test/components/latestEntriesTable.test.tsx, apps/web/test/components/search.test.tsx
=> Fix Page Input No Result Display and Query Missing on Refresh

packages/ui/src/ERC20DepositForm.tsx, packages/ui/src/ERC721DepositForm.tsx, packages/ui/src/EtherDepositForm.tsx, packages/ui/src/RawInputForm.tsx, packages/ui/src/hooks/useUndeployedApplication.ts, packages/ui/test/ERC20DepositForm.test.tsx, packages/ui/test/EtherDepositForm.test.tsx, packages/ui/test/RawInputForm.test.tsx, packages/ui/test/hooks/useUndeployedApplication.test.ts
I tweaked the behaviour of applications autocomplete field so that the check for undeployed application is evaluated 1 second after the latest batch of applications is pulled. This way the related warning won't appear while the applications query is executed in the background.
To achieve this, I added a custom hook called `useUndeployedApplication`.
=> #119 Tweak warning for undeployed application

apps/web/package.json, yarn.lock
I upgraded next to the latest version and tested the app afterwards. I didn't notice any issues and according to the [docs](https://nextjs.org/blog/next-14-1) most changes affect self-hosting, dev builds performance, dx, parallel/intercepted routes so I think we are safe to upgrade.
Looking at the next repo I did notice a couple of issues reported related to 14.1 - https://github.com/vercel/next.js/issues/61002 and https://github.com/vercel/next.js/issues/62727. However, both seem to be resolved in 14.1.4.
I also tested this one from a docker container and didn't notice any issues. The app works as expected.
=> #147 Upgrade nextjs to latest version

packages/rollups-wagmi/package.json, yarn.lock
I upgraded `@cartesi/rollups` package to `1.2`. The wagmi code generated worked as expected afterwards. I also tested all transaction forms and they worked ok so no regressions found.
=> #149 Upgrade @cartesi/rollups package

apps/web/graphql/queries.graphql, apps/web/src/app/applications/page.tsx, apps/web/src/components/applications/applications.tsx, apps/web/src/components/applications/userApplicationsRow.tsx, apps/web/src/components/applications/userApplicationsTable.tsx, apps/web/src/components/entriesSummary.tsx, apps/web/src/components/paginated.tsx, apps/web/test/components/applications/userApplicationRow.test.tsx, apps/workshop/src/stories/Summary.stories.tsx, packages/ui/src/Summary.tsx, packages/ui/test/Summary.test.tsx
=> 116. Implement application overview card and table

apps/web/src/app/applications/[address]/inputs/page.tsx, apps/web/src/app/applications/[address]/page.tsx, apps/web/src/components/applications/applicationSummary.tsx, apps/web/src/components/applications/latestInputsTable.tsx, apps/web/src/components/connection/connectionSummary.tsx, apps/web/src/components/latestEntries.tsx, apps/web/test/components/applications/applicationSummary.test.tsx, apps/web/test/components/applications/latestInputsTable.test.tsx, apps/web/test/components/applications/mocks.ts, apps/web/test/components/connection/connectionSummary.test.tsx, apps/web/test/components/connection/mocks.ts
I tweaked `/applications/{address}` route to display the application summary information with 4 cards for inputs, notices, vouchers and reports. Below the cards, I added the 6 latest inputs table.
=> #153 Add application summary

apps/web/e2e/pages/home.spec.ts, apps/web/src/components/entriesSummary.tsx, apps/web/src/components/latestEntries.tsx, packages/ui/src/Summary.tsx
I added e2e tests for the home page covering the summary cards for inputs and applications as well as the latest inputs and applications tables.
=> #168 Add e2e tests for home page

apps/web/src/components/applications/applicationRow.tsx, apps/web/src/components/applications/applications.tsx, apps/web/src/components/applications/userApplicationsRow.tsx, apps/web/test/components/applications/applicationRow.test.tsx, apps/web/test/components/applications/userApplicationRow.test.tsx
Code changes to add access to an application's summary page from the `/applications` page. Also, include a small change to avoid unintended rewrites in the query parameters done by the component not selected, i.e., the only mounted component is the one under the selected tab.
=> Feat: Application summary page access

apps/web/src/components/applications/applicationRow.tsx, apps/web/src/components/applications/applicationsTable.tsx, apps/web/src/components/applications/userApplicationsRow.tsx, apps/web/src/components/applications/userApplicationsTable.tsx, apps/web/src/components/inputs/inputsTable.tsx, apps/web/src/components/tableResponsiveWrapper.tsx, apps/web/test/components/applications/applicationRow.test.tsx, apps/web/test/components/applications/applications.test.tsx, apps/web/test/components/applications/userApplicationRow.test.tsx
I made the applications and user applications table responsive. I also made some slight refactoring for a couple of components. Additionally, I made a [task](https://github.com/cartesi/rollups-explorer/issues/178) about extracting this repetitive responsive table logic into a reusable component.
=> #171 Make applications tables responsive

apps/web/e2e/pages/applicationInputs.spec.ts, apps/web/e2e/utils/navigation.ts, apps/web/src/components/applications/applicationsTable.tsx, apps/web/src/components/inputs/inputRow.tsx
I added e2e tests and also a reusable navigation util for going to the application inputs page.
=> #190 Add e2e tests for application inputs page

apps/web/src/components/sendTransaction.tsx, apps/web/src/lib/methodResolver.ts, apps/web/test/lib/methodResolver.test.ts, docker/Dockerfile, packages/ui/src/AddressRelayForm.tsx, packages/ui/src/DepositFormTypes.ts, packages/ui/src/ERC1155DepositForm/types.ts, packages/ui/src/index.tsx, packages/ui/test/AddressRelayForm.test.tsx, packages/ui/test/utils/stubs.ts
Code changes to add support to use the `DappAddressRelay` to inform off-chain machine the address of the Dapp contract. More details  on #185.
=> Feature: Add support to DappAddressRelay 

apps/web/src/components/networks/cartesiScanNetworks.tsx
Code changes to add a new main icon for Base on `CartesiScanNetwork` component.
=> Fix: Include main icon for Base

packages/ui/src/InputDetails/Content.tsx
Apply code changes to improve readability in the input-details area. When the input payload is in a valid JSON format, the content inside the `<TextArea />` will be formatted to give better readability. 
I noticed a few oddities within the data already on-chain. Below are examples: One is a valid JSON format, and the other looks like one, but it is a string escaping other strings, therefore formatting will not be applied. 
Good format:
```JSON
{"name": "my-app-action", "value":"some_value"}
```
Bad format: 
```JSON
"{\"method\":\"create_something\",\"data\":{}}"
```
=> feat: Add formatting for JSON content in the input-details.

apps/workshop/package.json, packages/ui/package.json, packages/ui/test/ERC1155DepositForm/BatchDeposit.test.tsx, yarn.lock
I'm bumping rainbow-kit, wagmi, to have access to the [Coinbase Smart Wallet](https://www.smartwallet.dev/why). I also bumped viem to its latest version. It was a bump direct on `yarn.lock`, so there were no changes on any `package.json` directly as the `semver` rule is already covering the ranges.
=> Chore: Rainbowkit + Wagmi (Coinbase Smart Wallet support)

.github/workflows/ci.yml, .github/workflows/e2e.yml, .gitignore, apps/web/additional.d.ts, apps/web/e2e/pages/applicationInputs.spec.ts, apps/web/e2e/pages/connections.spec.ts, apps/web/e2e/utils/connection.ts, apps/web/playwright.config.ts, package.json, turbo.json
I created a new `e2e` workflow for the e2e tests. It runs on successful deployment and is triggered only if the deployment is for the `rollups-explorer-sepolia` environment. This way, we can use the produced vercel preview url as base url for the e2e tests. 
I had to use Protection Bypass for Automation from the vercel settings, otherwise the e2e tests were failing because they were hitting the vercel login page.
=> #193 Add build step for e2e tests

.github/workflows/e2e.yml, apps/web/e2e/menu.spec.ts, apps/web/e2e/pages/applicationInputs.spec.ts, apps/web/e2e/pages/inputs.spec.ts, apps/web/graphql/rollups/queries.graphql, apps/web/src/components/connection/connectionInputStatusBadge.tsx, apps/web/src/components/inputs/inputRow.tsx, apps/web/src/components/inputs/inputsTable.tsx, apps/web/test/components/connection/connectionInputStatusBadge.test.tsx, apps/web/test/components/inputs/inputRow.test.tsx, apps/web/test/components/inputs/inputsTable.test.tsx, docker/Dockerfile, package.json, reportGitHubCheckStatus.mjs, yarn.lock
I added the input completion status and also covered the new logic with unit tests.
=> #186 Add input completion status

apps/web/src/components/applications/applicationsTable.tsx, apps/web/src/components/responsiveTable.tsx, apps/web/test/components/responsiveTable.test.tsx
I added a `ResponsiveTable` component and utilised it on the applications page for the time being.
=> #178 Create responsive table component

packages/ui/src/RawInputForm.tsx, packages/ui/test/RawInputForm.test.tsx
I added a segmented control to the Raw Input form and the ability to encode `utf-8` string into `hex`. Also, covered the functionality with unit tests.
=> #207 Add support for sending generic input

apps/web/src/components/inputs/voucherExecution.tsx, apps/web/test/components/inputs/voucherExecution.test.tsx
Summary:
- Made sure the Execute button remains disabled if the prepare call is pending or has failed
- Displayed an alert when the prepare call has failed with the relevant error message
- Displayed `Preparing voucher...` text in the button for voucher execution while the prepare call is pending
- Refactored types within the `VoucherExecution` component
=> #216 Improve voucher execution error handling

.github/workflows/ci.yml, .github/workflows/e2e.yml, apps/web/e2e/pages/applicationSummary.spec.ts, apps/web/e2e/utils/connection.ts, apps/web/e2e/utils/navigation.ts, apps/web/src/components/applications/applicationSummary.tsx, reportGitHubCheckStatus.mjs
I added e2e tests for the application's summary page and also extended the e2e utils a bit.
=> #189 Add e2e tests for application's summary page

apps/web/package.json, yarn.lock
I upgraded NextJS to its latest version and tested for regressions. I didn't find any issues.
I did notice however some performance improvements in terms of the dev server speed - quicker initial build times and faster HMR. Also, turbopack seems to be in [stable state](https://nextjs.org/blog/next-14-2#turbopack-for-development-release-candidate) now, so maybe we can start using it with `next dev --turbo`.
=> #221 Upgrade NextJS

apps/web/src/components/sendTransaction.tsx, packages/ui/src/AddressRelayForm.tsx, packages/ui/src/ERC1155DepositForm/DepositFormBatch.tsx, packages/ui/src/ERC1155DepositForm/DepositFormSingle.tsx, packages/ui/src/ERC1155DepositForm/types.ts, packages/ui/src/ERC20DepositForm.tsx, packages/ui/src/ERC721DepositForm.tsx, packages/ui/src/EtherDepositForm.tsx, packages/ui/src/RawInputForm.tsx, packages/ui/test/AddressRelayForm.test.tsx, packages/ui/test/ERC20DepositForm.test.tsx, packages/ui/test/ERC721DepositForm.test.tsx, packages/ui/test/EtherDepositForm.test.tsx, packages/ui/test/RawInputForm.test.tsx
I implemented the `onSuccess` callback for all transaction forms and made that callback also required (instead of optional). Additionally, I had to tweak some unit.
=> #222 Update alerts for transaction forms

apps/web/src/components/inputs/voucherExecution.tsx, apps/web/test/components/inputs/voucherExecution.test.tsx, packages/ui/src/InputDetails/index.tsx, packages/ui/test/InputDetails/InputDetails.test.tsx
I tweaked the behaviour related to voucher execution so that the alert for the prepare error is only displayed if the voucher has a proof. I also made the error message a bit more informative so that users are aware that it's for the vouchers.
Additionally, I also disabled the `keepMounted` setting for the input details tabs so that voucher related logic is invoked only when the Vouchers tab is active.
I added a unit test for the voucher alert change and tweaked several for the input details that were failing.
=> #238 Fix voucher execution alert

apps/web/package.json, apps/web/src/components/specification/hooks/localRepository.ts, yarn.lock
Changes for the repository add method implementation to use UUID v4 as ID instead of time as a number. That avoids overrides for fast inserts (e.g. Specification imports)
**PS: This PR is targeting the branch-PR #232**
=> refactor: Specification ID generator

apps/web/e2e/transactions/depositEther.spec.ts
I added the following e2e tests for the ether deposit form:
- Test that the form is rendered correctly (correct fields, labels, etc)
- Test that the form correctly validates invalid inputs and displays correct error messages (invalid address, amount, hex for extra data layer)
- Test that the form correctly validates valid inputs and do not display any error messages (valid address, amount, hex for extra data layer)
I didn't add tests for the `Deposit` functionality because currently we use a 'dummy' test account that doesn't have any ETH available.
=> #204 Add e2e tests for ether deposit form

apps/web/src/components/inputs/inputDetailsView.tsx, apps/web/test/components/inputs/inputDetailsView.test.tsx, apps/web/test/utils/dataSamples.ts, packages/ui/src/InputDetails/Content.tsx, packages/ui/src/InputDetails/InputContent.tsx, packages/ui/src/InputDetails/PageableContent.tsx, packages/ui/test/InputDetails/InputDetails.test.tsx
I added the new `Decoded` segment and covered the new logic with unit tests. I added an `additionalControls` array prop to the `InputContent` component that currently supports only one value - 'decoded'.
=> #253 Add decoded section in input details

apps/web/src/components/specification/decoder.ts, apps/web/src/components/specification/systemSpecs.ts, apps/web/src/components/specification/types.ts, apps/web/test/components/specification/decoder.test.ts
I extended the SliceInstruction model with an `optional` boolean property. Also added the slice instruction for the `execLayerData` to the system specs for EtherPortal and ERC20Portal. Additionally, I extended the decoder to handle the new `optional` property and covered the logic with unit tests.
=> #252 Add capability to byte slice to be optional

apps/web/src/components/specification/SpecificationFormView.tsx, apps/web/src/components/specification/form/fields/ByteSlices.tsx, apps/web/test/components/specification/SpecificationFormView.test.tsx
I made a couple of small tweaks so that on small screens the `stack_screen` layout is automatically activated and the view switch is hidden. When resizing back to large screen, the view switch is shown again and the last selected view is activated.
=> #257 Tweak layout on small screens

README.md
A tiny documentation update to remove a "meaning" typo and clarify the monorepo package-installation link.
=> docs: Update monorepo package installation wording for clearer message.

apps/web/src/components/specification/form/fields/ByteSlices.tsx, apps/web/test/components/specification/SpecificationFormView.test.tsx
I added the optional field for byte slices under the ABI Parameters form and covered the new logic with unit tests.
=> #264 Add optional switch for byte slice

apps/web/package.json, apps/web/src/components/applications/applicationsTable.tsx, apps/web/src/components/applications/latestInputsTable.tsx, apps/web/src/components/latestEntries.tsx, apps/web/src/components/latestEntriesTable.tsx, apps/web/test/components/specification/SpecificationFormView.test.tsx, packages/ui/package.json, packages/ui/test/GenericInputForm/index.test.tsx, yarn.lock
The upgrade will fix a problem caused by caching logic inside the `abitype` library. An issue was raised explaining the case, and they fixed and released it. More details are in the issue link below. Also, a standalone abitype dependency was removed and all imports and usage replaced by `viem`. Text fixes were also applied. 
Issue: [wevm/abitype#247](https://github.com/wevm/abitype/issues/247)
Release: [abitype/releases@1.0.7](https://github.com/wevm/abitype/releases/tag/abitype%401.0.7)
=> Fix: cached parseAbi inputs/outputs 

packages/ui/src/ERC20DepositForm.tsx, packages/ui/test/ERC20DepositForm.test.tsx
I tweaked the `enabled` logic for both `approve` and `deposit` calls so that they remain disabled until `amount` is larger than zero.
Besides adding new unit tests, I also had to slightly refactor some existing ones.
=> #279 Tweak approve and deposit calls for erc 20 form

apps/web/src/components/specification/components/DecodingPreview.tsx
I made the preview section sticky so that it's visible at all times.
=> #275 Make specs preview section sticky

apps/web/test/components/sendTransaction.test.tsx, packages/ui/src/EtherDepositForm.tsx, packages/ui/src/hooks/useFormattedBalance.ts, packages/ui/test/EtherDepositForm.test.tsx, packages/ui/test/hooks/useFormattedBalance.test.ts
I tweaked the validation for the ether deposit amount field so that it's compared to the balance of the logged user. I also covered the new logic with unit tests.
I had to slightly refactor some code related to the unit tests for that form, it's mostly related to the `wagmi` mocks. I had to either continue using the async mocking approach (which we decide to drop) for the new tests or refactor the code so that the standard "synchronous" mocking approach is used throughout the test suite. I went for the latter, I think this is ok because https://github.com/cartesi/rollups-explorer/pull/269 is on hold (which also touches the same files).
=> #280 Improve balance error for ether deposit form

apps/web/src/components/layout/shell.tsx, apps/web/test/components/layout/shell.test.tsx
Besides the functionality and tests for it, I also refactored the other tests in the `shell` test suite.
=> #295 Disable send transaction button when network is wrong

apps/web/next-env.d.ts, apps/web/src/components/applications/userApplicationsRow.tsx, apps/web/test/components/applications/userApplicationRow.test.tsx, package.json
Code changes to fix a bug when trying to list the connected user's application. It was looking at the ID property of the application that was composed of only the address, but it is not reliable as it is now composed with the chain it belongs to and it may have more information. So the `address` property is the correct property to use.
=> Bugfix: Applications my apps tab.

apps/web/e2e/pages/connections.spec.ts, apps/web/src/components/connection/connectionInfo.tsx, apps/web/test/components/connection/connectionInfo.test.tsx, apps/web/test/components/connection/connectionView.test.tsx
I added a confirmation modal for the connection deletion and also covered the new logic with unit and e2e tests.
I removed one of the unit tests in `connectionView` because it appeared to test the same connection removal logic as in `connectionInfo`.
=> #304 Add confirmation for deleting connection

apps/web/e2e/pages/specifications.spec.ts, apps/web/e2e/pages/specificationsNew.spec.ts, apps/web/src/components/specification/SpecificationListView.tsx
I added e2e tests for:
- `/specifications` page
- `/specifications/new` page
- `/specifications/edit` page
One of those tests caught an issue for the ABI Parameters that I logged [here](https://github.com/cartesi/rollups-explorer/issues/297).
=> #286 Add e2e tests for specifications pages

packages/ui/src/GenericInputForm/AbiFields.tsx, packages/ui/src/GenericInputForm/useGenericInputForm.ts, packages/ui/test/GenericInputForm/index.test.tsx
Besides the code changes and new unit tests for it, I also refactored the test suite for the generic form, removing inline imports.
=> #299 Disable existing JSON ABI specification option for generic input form when no specifications are available

apps/web/e2e/pages/connections.spec.ts, apps/web/next-env.d.ts, apps/web/src/app/connections/page.tsx, apps/web/src/app/specifications/page.tsx, apps/web/src/components/connection/components/NewConnectionButton.tsx, apps/web/src/components/connection/connectionView.tsx, apps/web/src/components/layout/pageTitle.tsx, apps/web/test/components/connection/connectionView.test.tsx
Code changes to make the connections page match the other pages. Also, change the overall presentation to have a similar behaviour to the Specification page (i.e., loading state, when there are no items, etc.). Also update the `page.ts` for specification to use the `PageTitle` component. _I am including screenshots._
Changes: 
- Update the connection page with a title and use the available `PageTitle` component.
- Update the overall presentation of the content of the connection, i.e. call to action to create a connection, fetching state and no items to be displayed to look similar to the Specification page. 
- Update the **specification page** to also use the `PageTitle` component rather than a standalone component.
- Update the `PageTitle` title to be of order `1` so it outputs an `h1` …
=> refactor: Update conn page to match other pages visual ID

apps/web/src/app/applications/[address]/inputs/page.tsx, apps/web/src/app/applications/[address]/page.tsx, apps/web/src/app/specifications/edit/[id]/page.tsx, apps/web/src/app/specifications/new/page.tsx, apps/web/src/components/address.tsx, apps/web/src/components/applications/applicationSummary.tsx, apps/web/src/components/applications/latestInputsTable.tsx, apps/web/src/components/connection/connectionInfo.tsx, apps/web/src/components/connection/connectionSummary.tsx, apps/web/src/components/connection/connectionView.tsx, apps/web/src/components/layout/pageTitle.tsx, apps/web/src/components/layout/shell.tsx, apps/web/src/components/networks/cartesiScanNetworks.tsx, apps/web/src/components/paginated.tsx, apps/web/src/components/specification/SpecificationListView.tsx, apps/web/src/components/specification/components/NewSpecificationButton.tsx, apps/web/src/components/specification/form/fields/ByteSlices.tsx, apps/web/src/components/specification/form/fields/Conditions.tsx, packages/ui/src/InputDetails/PageableContent.tsx, packages/ui/src/InputDetails/index.tsx, packages/ui/src/SummaryCard.tsx
Summary of the changes:
- Shortened the address in breadcrumbs.
- Changed inline page title for `/applications/:id` to `Application Summary` to make the title more explanatory.
- Changed inline page title for `/applications/:id/inputs` to `Application Inputs` to make the title more explanatory.
- Utilised `PageTitle` component on pages `/specifications/new` and `specifications/:id`.
- Tweaked gap between elements in the `Address` component to mitigate extra space between them and the copy button.
- Made the latest inputs table on `/applications/:id` page responsive.
- Fixed warning for duplicate keys for latest inputs table.
- Improved spacings for the connection card.
- Made the grid 2x2 for the application summary cards on small screens.
- Changed text for the create connection button …
=> #313 Improve responsive design on small devices

apps/web/mantine.d.ts, apps/web/src/components/layout/footer.tsx, apps/web/src/components/layout/shell.tsx, apps/web/src/providers/theme.tsx
Code changes to fix the visualisation of the Footer content on a Desktop size screen. The z-index of the navbar will vary based on screen size. The menu has a full-screen drawer effect on a small device, and it will be on top of the body and footer contents. Otherwise, the footer is above the navbar, as previously.  GIF below of the currently deployed version.
=> Fix: Navbar and footer z-index.

apps/web/src/components/applications/latestInputsTable.tsx, apps/web/src/components/latestEntries.tsx, apps/web/src/components/latestEntriesTable.tsx
While testing https://github.com/cartesi/rollups-explorer/pull/318 I noticed that a couple of tables are still not sufficiently responsive on small screens so I made several minor fixes to improve that.
=> feat(apps/web): Improve responsive design for latest entries tables

apps/web/src/components/inputs/inputs.tsx, apps/web/src/components/paginated.tsx, apps/web/src/components/search.tsx, apps/web/test/components/search.test.tsx
While working on https://github.com/cartesi/rollups-explorer/issues/323, I noticed some performance issues with the inputs search:
- The search was causing some of the Next.js's contexts (related to routing) to be re-rendered on each key stroke.
- The search was causing the table beneath it to re-render on each key stroke (whenever the search value was changing).
In some cases, when you are quickly typing in the search, this resulted in noticeable FPS drops (from ~60 to ~30). 
Here's a video demonstrating this:
https://github.com/user-attachments/assets/eb67ebff-4b2d-4afb-8331-1bee9627a100
I implemented a couple of minor tweaks in order to optimise this:
- The search will update the page query params using a debounced function.
- The table is memoized and doesn't re-render on each key …
=> #323 Improve inputs search performance

apps/web/e2e/pages/specificationsNew.spec.ts, apps/web/src/components/specification/form/fields/HumanReadableABIParameter.tsx, apps/web/src/components/specification/form/validations.ts, apps/web/test/components/specification/SpecificationFormView.test.tsx
I tweaked slightly the logic for adding abi params from the specs form. Now, when clicking on the `Add` button next to the abi params input, we'll first parse the params to ensure they're valid. Only if they are, we'll add them to the entries array.
I kept the validation for entries, this line:
```
const error = isNotNilOrEmpty(entries) ? checkError(entries) : null;
```
so that users can still see an error for the entries if they previously saved a spec with invalid params.
=> #297 Validate abi params entry when adding it

packages/rollups-wagmi/deployments/ApplicationFactory.json, packages/rollups-wagmi/deployments/AuthorityFactory.json, packages/rollups-wagmi/deployments/ERC1155BatchPortal.json, packages/rollups-wagmi/deployments/ERC1155SinglePortal.json, packages/rollups-wagmi/deployments/ERC20Portal.json, packages/rollups-wagmi/deployments/ERC721Portal.json, packages/rollups-wagmi/deployments/EtherPortal.json, packages/rollups-wagmi/deployments/InputBox.json, packages/rollups-wagmi/deployments/QuorumFactory.json, packages/rollups-wagmi/deployments/SafeERC20Transfer.json, packages/rollups-wagmi/deployments/SelfHostedApplicationFactory.json, packages/rollups-wagmi/package.json, packages/rollups-wagmi/tsconfig.json, packages/rollups-wagmi/wagmi.config.ts, yarn.lock
Bumping cartesi/rollups to its stable version.
=> chore: Bump rollups-contracts to its stable v2.

apps/web/e2e/pages/applications.spec.ts, apps/web/src/components/applications/applications.tsx, apps/web/src/components/inputs/inputs.tsx, apps/web/src/components/latestEntries.tsx, apps/web/src/components/paginated.tsx, apps/web/src/components/search.tsx, apps/web/src/lib/query.ts, apps/web/test/components/applications/applications.test.tsx, apps/web/test/lib/query.test.ts, packages/domain/graphql/queries.graphql
I added the applications search that handles application addresses or owners.
Additionally, I refactored the search input removing its wrapper with negative margins and created a slot in the `Paginated` component for it.
Finally, I covered the new logic with unit and e2e tests.
=> #351 Add applications search

packages/ui/src/hooks/useWatchQueryOnBlockChange.ts, packages/ui/src/utils/index.ts, packages/ui/test/hooks/useWatchQueryOnBlockChange.test.ts
The query key returned from `useReadContracts` had unstable reference that caused a re-invocation loop for `useWatchQueryOnBlockChange`. I fixed it by verifying the uniqueness of the query and block number in that hook.
=> #378 Fix issue with RPC requests

apps/web/e2e/pages/applications.spec.ts, apps/web/e2e/pages/inputs.spec.ts, apps/web/e2e/performance/applications.spec.ts, apps/web/e2e/performance/inputs.spec.ts, apps/web/e2e/transactions/metamask.spec.ts, apps/web/e2e/utils/requests.ts, apps/web/src/components/applications/applications.tsx, apps/web/src/components/inputs/inputs.tsx, apps/web/src/components/paginated.tsx, apps/web/src/components/versionsFilter.tsx, apps/web/test/components/versionsFilter.test.tsx
Summary of the changes:
- Added e2e tests for measuring the performance of the `/inputs` and `/applications` pages
- The tests measure the performance of pages 2 to 5
- The tests will fail if the combined time for them was more than 2 seconds
- The tests will fail if any request took more than 1 second
- Added e2e tests for verifying the caching for the `/inputs` and `/applications` pages
- Fix issues with flaky e2e tests for rollups v2 version filtering
- Removed the loading state from the filters button as there were cases where multiple loading states appear on the page:
=> #376 Add e2e test for performance measuring
