cartesi/rollups-explorer

- apps/web/src/providers/walletProvider.tsx
Code changes to prepare to set up a Vercel for the Mainnet network. In that project, the `NEXT_PUBLIC_ENABLE_TESTNETS` will be false and cause problems in the wallet connector setup. 
PS: No real changes in the imports, that was the formatter organising things
> feat: Add Mainnet for wallet connectors

- apps/web/graphql/queries.graphql
- apps/web/src/app/applications/[address]/page.tsx
- apps/web/src/app/page.tsx
- apps/web/src/components/inputRow.tsx
- apps/workshop/src/stories/Summary.stories.tsx
- packages/ui/src/Summary.tsx
- packages/ui/src/index.tsx
- turbo.json
There is a lot of duplicate code between the home page and the application page.
I wish there was less, but reducing the code necessary for the pagination, and extracting the InputRow and InputTable to a component in the UI package.
> Application page

- apps/web/src/components/inputRow.tsx
Small adjustment to remove decimal places of seconds of age of input
> Adjust age precision in input list

- apps/web/src/components/inputRow.tsx
- apps/workshop/.storybook/preview.tsx
- apps/workshop/.storybook/walletProvider.tsx
- apps/workshop/package.json
- apps/workshop/src/stories/ConnectButton.stories.tsx
- yarn.lock
Integrate RainbowKit into our storybook preview, so we can develop components that depend on the wallet context.
> Storybook wallet integration

- AUTHORS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
Add documentation about how to contribute, the licensing, the authors and the code of conduct. Also, an update in the project's readme, including structural information, some code standards to avoid noise, etc. 
Changes: 
* Added License file.
* Added Code of Conduct file.
* Added Contributing file.
* Added Authors file.
* Update the project's README file.
> docs: Community files + update to README

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- apps/web/graphql/queries.graphql
- apps/web/src/app/applications/[address]/page.tsx
- apps/web/src/app/applications/page.tsx
Page to list applications.
Still have to implement pagination.
> Applications page

- packages/ui/src/ERC20DepositForm.tsx
- packages/ui/test/ERC20DepositForm.test.tsx
> Improve allowance/balance UI on amount field for deposit ERC-20 Tokens

- apps/web/src/app/applications/[address]/page.tsx
- apps/web/src/app/applications/page.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/app/page.tsx
- apps/web/src/components/address.tsx
- apps/web/src/components/applications.tsx
- apps/web/src/components/breadcrumbs.tsx
- apps/web/src/components/entriesSummary.tsx
- apps/web/src/components/inputs.tsx
I added metadata to pages with the exception of `/inputs` which is a page that will be introduced with https://github.com/cartesi/rollups-explorer/pull/81. So I'll wait for #81 to be merged first, rebase and add the inputs metadata afterwards.
> #76 Add metadata to pages

- apps/web/src/components/inputs/inputRow.tsx
https://github.com/cartesi/rollups-explorer/assets/13269955/9fe96790-7c64-4d44-8eba-f130a58aad54
Close #100
> #100 Responsive Table on Safari have different behaviour

- apps/web/graphql/queries.graphql
- apps/web/src/components/inputs/inputs.tsx
- apps/web/src/components/inputs/inputsTable.tsx
- apps/web/src/components/paginated.tsx
- apps/web/src/components/search.tsx
- apps/web/src/hooks/usePaginationParams.tsx
- apps/web/src/hooks/useQueryParams.tsx
- apps/web/src/lib/query.ts
- apps/web/test/components/search.test.tsx
- apps/web/test/hooks/useQueryParams.test.tsx
> #111 Add search UI

- packages/ui/src/ERC721DepositForm.tsx
- packages/ui/src/hooks/useTokensOfOwnerByIndex.ts
- packages/ui/test/ERC20DepositForm.test.tsx
- packages/ui/test/ERC721DepositForm.test.tsx
- packages/ui/test/EtherDepositForm.test.tsx
- packages/ui/test/RawInputForm.test.tsx
- packages/ui/test/hooks/useTokensOfOwnerByIndex.test.ts
I added more unit tests for all transaction forms. I tried to cover all functionality and UI of those forms so we can increase stability for them.
> #127 Add unit tests for transaction forms

- apps/web/package.json
- apps/web/src/app/layout.tsx
- yarn.lock
Code changes will include the use of Vercel's web analytics. Get some insight related to the usage of the web application.
> chore: Add vercel web analytics.

- apps/web/src/app/connections/page.tsx
- apps/web/src/components/connection/connectionInfo.tsx
- apps/web/src/components/connection/connectionView.tsx
- apps/web/src/components/connection/connections.tsx
- apps/web/src/components/layout/shell.tsx
- apps/web/src/providers/theme.tsx
- apps/web/test/components/connection/connectionView.test.tsx
- apps/web/test/components/layout/shell.test.tsx
I added a settings group to the navbar. It contains a single nav link to the connections page. I also removed a couple of obsolete tests for `ConnectionView` component and added several for the `Shell` component.
> #150 Add connections page

- apps/web/src/app/applications/page.tsx
- apps/web/src/components/applications/applications.tsx
- apps/web/src/components/applications/userApplicationsTable.tsx
- apps/web/src/components/paginated.tsx
- apps/web/test/components/applications/applications.test.tsx
I added two tabs to the applications page to respectively display all apps table and my apps table. I also refactored slightly the `UsersApplications` component to utilise the `Paginated` component. Additionally, I covered the new logic with unit tests.
> #172 Add tabs to applications page

- apps/web/src/components/applications/latestInputsTable.tsx
- apps/web/src/components/inputs/inputRow.tsx
- apps/web/src/lib/methodResolver.ts
- apps/web/test/lib/methodResolver.test.ts
I added resolvers for the missing deposit types - ERC-721 and single/batch ERC-1155. I also refactored the code surrounding the method resolution and extracted it into a single module to keep things DRY. I also covered it with unit tests.
> #173 Add missing method name for deposits

- apps/web/package.json
- apps/web/src/app/layout.tsx
- yarn.lock
Code changes will include the use of Vercel's speed insights. Get some performance metrics.
> chore: Add vercel speed insights.

- apps/web/e2e/pages/connections.spec.ts
- apps/web/e2e/utils/connection.ts
- apps/web/src/components/connection/connectionForm.tsx
- apps/web/src/components/connection/connectionInfo.tsx
- apps/web/test/components/connection/connectionForm.test.tsx
I added e2e tests and also a util for creating connections.
> #188 Add e2e tests for connections page

- apps/web/.env.base-mainnet
- apps/web/.env.base-sepolia
- apps/web/src/components/networks/cartesiScanNetworks.tsx
- apps/web/src/providers/walletProvider.tsx
- apps/web/test/components/layout/shell.test.tsx
- apps/web/test/components/networks/cartesiScanNetworks.test.tsx
Code changes to support base and base-sepolia. Also, add the Base logo and links in the `CartesiScanNetworks` component.
> feat: Add support base and base-sepolia networks.

- apps/web/src/components/inputs/inputsTable.tsx
- apps/web/test/components/inputs/inputsTable.test.tsx
I hid the status tooltip if there are already some connections added.
> #214 Hide status tooltip if there are some connections

- apps/web/src/components/networks/cartesiScanNetworks.tsx
- apps/web/src/providers/walletProvider.tsx
- apps/web/test/components/layout/shell.test.tsx
- apps/web/test/components/networks/cartesiScanNetworks.test.tsx
Code changes to add support to Arbitrum Mainnet and Sepolia.
> feat: Add arbitrum support

- apps/web/e2e/pages/inputs.spec.ts
Fix for the flaky e2e test that is causing the e2e job to fail.
> Fix flaky e2e test

- apps/web/src/components/specification/SpecificationListView.tsx
- apps/web/test/components/specification/SpecificationListView.test.tsx
I added a confirmation modal for the specification deletion and also covered the new logic with unit tests.
> #302 Add confirmation for deleting specification

- apps/web/src/components/specification/components/SpecificationsActionsMenu.tsx
I replaced the nested button with a `Box` instead.
> #335 Fix buttons nesting

- apps/web/src/components/layout/shell.tsx
- apps/web/src/components/sendTransaction.tsx
- apps/web/test/components/sendTransaction.test.tsx
- apps/web/test/utils/WithMantineTheme.tsx
- packages/ui/src/AddressRelayForm.tsx
- packages/ui/src/ApplicationAutocomplete.tsx
- packages/ui/src/ERC1155DepositForm/DepositFormBatch.tsx
- packages/ui/src/ERC1155DepositForm/DepositFormSingle.tsx
- packages/ui/src/ERC20DepositForm/index.tsx
- packages/ui/src/ERC721DepositForm/index.tsx
- packages/ui/src/EtherDepositForm/index.tsx
- packages/ui/src/GenericInputForm/index.tsx
- packages/ui/test/ApplicationAutocomplete.test.tsx
- packages/ui/test/utils/WithMantineTheme.tsx
I made the tweaks described in https://github.com/cartesi/rollups-explorer/issues/383. I also added unit tests for the changed logic and did a bit of refactoring.
> #383 Tweaks for deposit forms
